name: PHPStan

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - 8.5
        dependencies:
          - locked

    name: PHPStan on PHP ${{ matrix.php }} - ${{ matrix.dependencies }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, phpstan:2
          coverage: none

      - name: Composer install
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run static analysis
        run: phpstan analyze
