name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
        dependencies:
          - lowest
          - locked
          - highest

    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.dependencies }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Composer install
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run tests
        run: composer test
