name: PHPUnit Coverage (Codecov)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-with-coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - 8.4
        dependencies:
          - locked

    name: Coverage on PHP ${{ matrix.php }} - ${{ matrix.dependencies }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: pcov

      - name: Composer install
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run tests
        run: composer test -- --coverage-clover coverage.xml --log-junit junit.xml

      - name: Upload coverage report
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # 5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # 1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
